repos:
  - name: dev
    description: Dev repo for dev/preprod clusters
    url: https://github.com/migrx-io/projectset-crds.git
    branch: main
    token: <token>
  - name: prod
    description: Prod repo for production clusters
    url: https://github.com/migrx-io/projectset-crds.git
    branch: main  
    token: <token>

roles:
  user:
    projectset:
      edit:
        - labels
        - annotations
        - namespace
        - template

  admin:
    projectset:
      edit:
        - labels
        - annotations
        - namespace
        - template
    projectsettemplate:
      edit:
        - labels
        - annotations
        - namespace
