repos:
  - name: test-ocp-cluster
    description: Dev repo for dev/preprod clusters
    url: https://github.com/migrx-io/projectset-crds.git
    branch: main
    token: <token>
    conf_file: projectsets.yaml
  - name: prod-ocp-cluster
    description: Prod repo for production clusters
    url: https://github.com/migrx-io/projectset-crds.git
    branch: main  
    token: <token>
    conf_file: projectsets.yaml

roles:
  user:
    projectset:
      edit:
        - labels
        - annotations
        - namespace
        - template
  admin:
    projectset:
      edit:
        - labels
        - annotations
        - namespace
        - template
    projectsettemplate:
      edit:
        - labels
        - annotations
        - namespace
