# apiVersion: v1
# kind: Namespace
# metadata:
#   labels:
#     app.kubernetes.io/component: projectset-api
#     app.kubernetes.io/name: namespace
#     app.kubernetes.io/part-of: projectset-api
#   name: projectset-api-system
# ---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: projectset-api
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: projectset-api
  name: projectset-api-service
  namespace: projectset-api-system
spec:
  ports:
  - name: http
    port: 8082
    protocol: TCP
    targetPort: http
  selector:
    name: projectset-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: projectset-api
    app.kubernetes.io/name: deployment
    app.kubernetes.io/part-of: projectset-api
    name: projectset-api
  name: projectset-api
  namespace: projectset-api-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: projectset-api
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: projectset-api
      labels:
        name: projectset-api
    spec:
      containers:
      - image: migrx/projectset-api:0.1.0
        name: projectset-api
        env:
        - name: APP_CONF
          value: "/app/secret/app.yaml"
        ports:
        - containerPort: 8082
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL

        volumeMounts:
          - mountPath: "/app/secret"
            name: app-conf
            readOnly: true

      volumes:
        - name: app-conf
          secret:
            secretName: app-conf
